spring:
  cache:
    jcache:
      config: classpath:ehcache.xml
#  h2:
#    console:
#      enabled: true
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: ${MARIA_URL}
    username: ${MARIA_USER}
    password: ${MARIA_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
    mongodb:
      host: ${MONGO_HOST}
      port: ${MONGO_PORT}
      database: ${MONGO_DATABASE}
      authentication-database: zupzup, admin
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            redirect-uri: "{baseUrl}/{action}/oauth2/code/{registrationId}"
            scope: email, profile, openid

oidc:
  google:
    iss: https://accounts.google.com
    iss2: accounts.google.com

client:
  url: ${CLIENT_URL}
  redirect:
    login-success: ${CLIENT_REDIRECT_LOGIN_SUCCESS}

jwt:
  secret-key: ${JWT_SECRET_KEY}
  auth-token-expired_second: 60
  access-expired-second: 7200
  refresh_expired_second: 1209600

management:
  endpoints:
    enabled-by-default: false
    jmx:
      exposure:
        exclude: "*"
    web:
      exposure:
        include: health, info, metrics
  endpoint:
    health:
      enabled: true
    info:
      enabled: true
    metrics:
      enabled: true
  server:
    port: ${HEALTH_PORT}