spring:
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: create
    open-in-view: false
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  data:
    mongodb:
      uri: ${MONGO_URI}
      database: ${MONGO_DATABASE}

server:
  servlet:
    context-path: /api

